name: Auto Deploy to Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: shurik
        TARGET: /home/shurik/tg_bot/
        SCRIPT_BEFORE: |
          cd /home/shurik/tg_bot
          /home/shurik/deploy.sh
